config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'articles', to: 'articles#index', as: :articles

  get    "articles/new",      to: "articles#new",  as: :new_article
  post   "articles",          to: "articles#create"

  # NB: The `show` route needs to be *after* `new` route.
  get    "articles/:id",      to: "articles#show", as: :article
  get    "articles/:id/edit", to: "articles#edit", as: :edit_articles
  patch  "articles/:id",      to: "articles#update"

  delete "articles/:id",      to: "articles#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<ul>
  <% @articles.each do |article| %>
  <div class="card m-1 border-0 mx-auto" style="width: 800px;">
    <h2 class="font-weight-normal"><%= link_to "#{article.title}", article_path(article) %></h2>
    <p class="font-weight-light"><%= article.content %></p>
  </div>
  <% end %>
</ul>

app/views/articles/new.html.erb
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<div class="card border-0">
  <div class="card mx-auto my-3 border-top-0 border-left-0 border-right-0 border-bottom" style="width: 800px;">
    <div class="container">
      <div class="row">
        <h2 class="font-weight-normal mr-4"><%= @article.title %></h2>
        <p class="mx-2"><%= link_to "Edit", edit_articles_path(@article) %></p>
        <p class="mx-2"><%= link_to "Delete",
                article_path(@article),
                method: :delete,
                data: { confirm: "Are you sure?" } %></p>
        <a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/restaurants/2">
        </a>
        </div>
    </div>
  </div>
  <div class="card mx-auto border-0" style="width: 800px;">
    <p class="font-weight-light"><%= @article.content %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body>
    <nav class="navbar navbar-light bg-light mb-3 border">
      <p class="text-secondary"><%= link_to "Wikinimous", articles_path %></p>
      <p class="text-secondary"><%= link_to "New Article", new_article_path %></p>
    </nav>

    <%= yield %>
  </body>
</html>